### ISSUE TITLE
[custom dashboard] Cannot add new link

### ISSUE THREAD

**Issue by MLOpsGuy** [deployKF/website#143]
Hi, I would like to custom the dashboard. For this, I added :

```yaml
      documentationItems:
        - text: deployKF Website
          desc: The tool that deployed your ML platform!
          link: https://github.com/deployKF/deployKF
        - text: POUET
          desc: Amazing web site
          link: https://www.pouet.net/
```
in `deploykf_core.deploykf_dashboard.navigation` in `generator/default_values.yaml`.

I deployed deployKF with ArgoCD and the official GitHub repo.

Do you have any idea why `POUET` website didn't appear in the dashboard?

_PS: Same thing for `externalLinks`:_

```yaml
      externalLinks:
        - text: POUET
          url: "/pouet/"
          icon: image:blur-linear
```
